---
apiVersion: v1
kind: Pod
metadata:
  name: pod-file-cm
spec:
  containers:
    - name: pod-file-cm
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/nginx/nginx.conf" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
  restartPolicy: Never