---
apiVersion: v1
kind: Pod
metadata:
  name: pod-env-cm
spec:
  containers:
    - name: pod-env-cm
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "printenv | grep netology.ru" ]
      envFrom:
      - configMapRef:
          name: domain
  volumes:
    - name: domain
      configMap:
        name: domain
  restartPolicy: Never