apiVersion: v1
kind: Pod
metadata:
  name: secret-files-pod
spec:
  containers:
    - name: test-container-files
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "sleep 600" ]
      volumeMounts:
      - name: creds
        mountPath: "/opt/creds"
        readOnly: true
      - name: cert
        mountPath: "/opt/cert"
        readOnly: true
  restartPolicy: Never
  volumes:
  - name: creds
    secret:
      secretName: credentials
      optional: false # default setting; "credentials" must exist
  - name: cert
    secret:
      secretName: domain-cert